### ISSUE TITLE
Feature Request: Reactions

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [AllanWang/Frost-for-Facebook#1725] opened 2020-10-21 03:25 UTC
Hey there,

Thank you very much for this awesome app.

I was wondering if it'd be possible to add reactions in messenger, etc. It seems that FB app allows one to long-tap on a video and add a reaction to it, or long-tap a message and add a reaction to it. And that feature seems to be lacking in Frost. Is it possible to implement it?

**Comment by AllanWang** [comment] 2020-11-08 01:49
Duplicate of #1667 

Removing as duplicate since all this requires conversion to messenger.com which is different from touch.facebook.com/messages

**Closed as completed by AllanWang** 2020-11-08 01:49 UTC
Labels: feature request
