### ISSUE TITLE
2 Account does not stay logged in

### ISSUE THREAD

**Issue by west89** [AllanWang/Frost-for-Facebook#1757] opened 2021-02-11 08:20 UTC
**Describe the bug**
If you want to switch to the second Facebook account, you get the login screen and have to log in again.
De logingegevens worden niet opgeslagen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Hamburger menu'
2. Click on 'Change account'
3. See error

**Details (please provide at least the app version):**
 - App Version:3.0.0
 - Device: Oneplus 8T
 - Android Version:10

**Comment by ghost** [comment] 2021-02-26 20:58
Preconditions: clear app data for Frost, only set amoled theme and verbose logging after first logging in an account. Keepass2Android is for Auto-fill service.

Steps:
1. Open frost
2. log in with first account
3. select amoled theme
4. go to settings, enable verbose logging
5. switch from wifi to mobile network
6. log in second account
7. switch back to wifi
8. switch to first account
9. first account got logged out
10. switch back to mobile network
11. second account is logged out
12. Frost has no accounts logged in

Basically it goes like this:
`[02-27 04:35:16.689 22680:23592 D/Frost]
Sign up button found; load login

[02-27 04:35:16.702 22680:22680 D/Frost]
Logging out user

[02-27 04:35:16.717 22680:22680 D/Frost]
Fb cookie deleted
`
Here are two logcat produced using that preconditions and steps above
[logcat_02-27-2021_04-36-18.txt](https://github.com/AllanWang/Frost-for-Facebook/files/6052453/logcat_02-27-2021_04-36-18.txt)s 
[logcat_02-27-2021_04-35-31.txt](https://github.com/AllanWang/Frost-for-Facebook/files/6052451/logcat_02-27-2021_04-35-31.txt)

**Comment by AllanWang** [comment] 2021-02-26 21:17
Duplicate of #1753.

In short, this is a new bug in 3.0.0.

For some reason the login page is showing, and I'm not sure if it's caused by messenger. Feel free to revert to the previous build for the time being. 

Closing this issue for now, so feel free to add more comments in the other issue. I faced this issue upon release, and I'm sure messenger caused a bunch of other problems.

**Closed as completed by AllanWang** 2021-02-26 21:17 UTC
Labels: bug, unverified
