### ISSUE TITLE
Does Not Save Log In Credentials

### ISSUE THREAD

**Issue by puppykickr** [AllanWang/Frost-for-Facebook#1587] opened 2019-11-26 08:23 UTC
- [ √] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**

When logging out, options appear.
One of them is to save the info and then log out.
This is what I choose.
The app does not remember any login info.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'  LOGOUT
2. Click on '....'  LOGOUT
3. Select '....'  SAVE INFO AND LOGOUT
4.  TRY TO LOG BACK IN
5. See error

**Details (please provide at least the app version):**
 - App Version:  2.4.1
 - Device:  ZTE558VL  
 - Android Version:  7.1.1

**Comment by AllanWang** [comment] 2019-11-26 08:48
This is intended behaviour. Frost has its own account manager, so it also doesn't make sense to provide more interactions upon log out. I may look into exiting the screen once that option appears, just like how I hide one tap logins for new logins

**Comment by puppykickr** [comment] 2019-11-26 09:33
If it has its own account manager, then wouldn't it be able to save the information?

**Comment by AllanWang** [comment] 2019-11-26 09:34
You can. Open the nav drawer, click the top area, and then add an account. No need to log out

**Comment by AllanWang** [comment] 2019-12-26 19:46
Closing as a solution already exists

**Closed as completed by AllanWang** 2019-12-26 19:46 UTC
Labels: feature request, low priority
