### ISSUE TITLE
Switching back to Frost shows home page

### ISSUE THREAD

**Issue by smnthermes** [AllanWang/Frost-for-Facebook#1539] opened 2019-09-15 02:32 UTC
- [x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
Frequently, the home page is showed again after switching back to Frost

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a post
2. Switch to other app
3. Switch back to Frost

**Details (please provide at least the app version):**
 - App Version: 2.3.2
 - Device: Motorola Moto G 2015
 - Android Version: 9

**Comment by AllanWang** [comment] 2019-09-15 02:38
How are you switching back to Frost? Currently, posts should be opened in a web overlay, and not the main activity. So long as that isn't closed, it should still exist.

**Comment by alekksander** [comment] 2019-09-15 11:22
@smnthermes isn't this issue related to android itself? sounds system is removing it from memory as background app…?

**Comment by smnthermes** [comment] 2019-09-22 19:02
I had disabled the overlay due to issues, but they have been fixed after 2.4.0.

**Comment by AllanWang** [comment] 2019-09-22 19:03
Are you saying this problem occurs with overlay enabled?

**Comment by smnthermes** [comment] 2019-10-16 16:45
I'm reopening this issue because after switching back to Frost, it always shows the first page of the overlay.

**Comment by AllanWang** [comment] 2019-10-16 17:15
For marketplace or all pages? I have a fixed push for the next update at #1578

**Comment by AllanWang** [comment] 2019-10-16 17:16
Actually that's a different problem. If it's a matter of switching apps and back, I still can't replicate. The overlay remains open when I go to another app

**Comment by smnthermes** [comment] 2019-10-17 15:17
My phone has 1 GB of RAM, but this isn't the sole cause of the problem. At m.facebook.com, the page reloads when switching back to the browser, but at least it remains on the page I was viewing previously.

**Comment by alekksander** [comment] 2019-10-17 20:19
i guess it's ram related after all. wouldn't a session restore like behavior be the way to go?

**Comment by smnthermes** [comment] 2019-10-18 21:40
@alekksander the browser at m.facebook.com remembers the previously viewed post, but Frost doesn't

**Comment by AllanWang** [comment] 2019-10-19 01:41
The browser does not use overlays, so if you want to have the same behaviour, you can disable them. You may experience problems of going back to the home page since we also don't have new windows, but that will be fixed in #1578. Closing as not reproducible for my devices, and there is an alternative

**Comment by smnthermes** [comment] 2019-10-19 14:47
@AllanWang when I disable overlays, Frost simply returns to the news feed. #1578 is related to a different problem, which also happens when using Facebook in a browser.

**Comment by AllanWang** [comment] 2019-10-20 04:42
When you open Frost again does it show the start screen or does it refresh?

**Comment by AllanWang** [comment] 2020-01-21 01:00
Closing due to nonresponse and non-reproducibility

**Closed as completed by AllanWang** 2020-01-21 01:00 UTC
Labels: bug, unverified
