### ISSUE TITLE
IABBinder.kt line 145

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#273] opened 2017-09-12 13:25 UTC
#### in com.pitchedapps.frost.utils.iab.IABSettings$restorePurchases$1$1.invoke

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59b7e056be077a4dcc81c973?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59b7e056be077a4dcc81c973?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment] 2017-09-17 03:18
Duplicate of #274

**Closed by AllanWang** 2017-09-17 03:18 UTC
Labels: wontfix
