### ISSUE TITLE
Full size image link doesn't work

### ISSUE THREAD

**Issue by jonbarh** [AllanWang/Frost-for-Facebook#1832] opened 2021-10-08 10:47 UTC
Yes, I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

Whenclick on link below any image to see it at full size, download it or share.

Steps to reproduce the behaviour:
1. Go to any image
2. Click on 'See full size image' (don't know the exact name in english)
3. Blank page occurs, info, download and share links are in, but neither of them works as expected.

 - App Version: 3.1.1
 - Device: POCOPHONE F1
 - Android Version: 10

![IMG_20211008_124616](https://user-images.githubusercontent.com/12173190/136543735-e7c438cb-40c4-43ad-894f-4d514e615a62.jpg)
![Screenshot_2021-10-08-12-46-25-136_com pitchedapps frost](https://user-images.githubusercontent.com/12173190/136543773-5c83189a-667a-4a0b-945f-b81b07b01192.jpg)

**Comment by mormegil-cz** [comment] 2021-10-09 10:12
Duplicate of #1823, I think.

**Comment by poppypundit** [comment] 2021-10-15 21:41
Face the same issue.

**Comment by swarupbhc** [comment] 2021-11-04 06:55
![Screenshot_20211104-122432_Frost](https://user-images.githubusercontent.com/55395995/140270414-2b497064-667b-439c-97d5-588f5ee0ceed.png)
Facing same issue 😓

**Closed as completed** 2021-11-20 05:56 UTC
Labels: bug, unverified
