### ISSUE TITLE
Multiple Account doesn't work 

### ISSUE THREAD

**Issue by MustafaMemisogM** [AllanWang/Frost-for-Facebook#1792] opened 2021-08-25 15:52 UTC
Hi, the feature multiple accounts doesn't work. If switch the account both account is sign out. 

 - App Version:Version 3.0.0
 - Android Version:10 QKQ1.190910.002

**Comment by MostWanted-Hub** [comment] 2021-09-11 14:37
Same problem on JoyUI  / miUi , I can't stay logged in

**Comment by AllanWang** [comment] 2021-09-12 08:32
Duplicate of #1753

**Closed as completed by AllanWang** 2021-09-12 08:32 UTC
Labels: bug, unverified
