### ISSUE TITLE
No notifications on A13

### ISSUE THREAD

**Issue by m0yP** [AllanWang/Frost-for-Facebook#1938] opened 2023-05-04 02:25 UTC
- [X] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
There's no way to enable notifications on Android 13. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Settings'
2. Click on 'Notifications'
3. Click on 'Customize notification channels'

**Details (please provide at least the app version):**
 - App Version: 3.2.0
 - Device: Poco X3 Pro (vayu)
 - Android Version: 13 (crDroid 9.4)

**Logs/Screenshots:**

![Screenshot_20230503-201654_Settings_1](https://user-images.githubusercontent.com/22119314/236097560-24281f64-9c7a-458f-a923-b97d312b72a1.png)

**Comment by LoneFenris** [comment] 2023-05-10 13:31
Likely duplicate of #1920

**Comment by m0yP** [comment] 2023-05-10 19:03
> Likely duplicate of #1920

That's correct, let me close this. Thx.

**Closed as not planned** 2023-05-10 19:03 UTC
Labels: bug, unverified
