### ISSUE TITLE
GitHub Button: Cannot resolve browser

### ISSUE THREAD

**Issue by toas-koas** [AllanWang/Frost-for-Facebook#1831] opened 2021-10-08 05:04 UTC
- [ x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
When I go to the settings and click on the GitHub button, it's says: Cannot resolve browser. 

**Details (please provide at least the app version):**
 - App Version 3.1.0
 - Device: Google Pixel 2XL
 - Android Version: 11

The Bug is not in the Version 3.1.0-9-355d8ae-test

**Comment by AllanWang** [comment] 2021-10-08 06:52
Duplicate of #1812

**Closed as completed by AllanWang** 2021-10-08 06:52 UTC
Labels: bug, unverified
