### ISSUE TITLE
downloadfile.bin

### ISSUE THREAD

**Issue by KaiFujiro** [AllanWang/Frost-for-Facebook#1827] opened 2021-10-02 02:38 UTC
I have a problem when I want to download images or videos in the comments column, everything changes to "downloadfile.bin" before in version 3.0.0 it's not like that, but since version 3.1.0 it's like that.

I'm using frost version 3.1.1 and android 5.1.1

**Comment by KaiFujiro** [comment] 2021-10-02 02:46
[logcat_10-02-2021_09-44-10.txt](https://github.com/AllanWang/Frost-for-Facebook/files/7270785/logcat_10-02-2021_09-44-10.txt)

**Comment by Red3miasto** [comment] 2021-10-02 15:30
Same here-  after update is impossible to opena pictures in full screen.
Lenovo P2 with LineageOS

**Comment by mormegil-cz** [comment] 2021-10-09 10:13
Duplicate of #1823, I think.

**Comment by Quackdoc** [comment] 2021-10-16 02:02
the .bin file is an html file it seems to be trying to download webpage instead of the image.

**Comment by AllanWang** [comment] 2021-11-22 06:06
Duplicate of #1823 

Fixed in #1855

**Closed as completed by AllanWang** 2021-11-22 06:06 UTC
Labels: bug
