### ISSUE TITLE
Cannot play videos with sound

### ISSUE THREAD

**Issue by sreejithpm92** [AllanWang/Frost-for-Facebook#1368] opened 2019-03-17 03:09 UTC
This issue started occuring very recently....When I play a video, by default the sound is muted in fb. But when I touch the unmute button, the video stops playing. I can't resume the playback anymore.

Please resolve this issue.

**Comment by AllanWang** [comment] 2019-03-20 13:21
Did they previously open the video overlay? And now it does nothing beyond stopping the video?

**Comment by sreejithpm92** [comment] 2019-03-20 14:15
Previously the videos used to play with sound.....and it's perfectly fine when browsing m.facebook.com. But, videos stop playing all of a sudden when i click unmute button in Frost. 
I recently discovered a workaround. It might help you to fix the bug. When I click the unmute button, the video stops playing. After that, when I click on the post, it opens a new window within Frost. Then, the video that stopped playing in my newsfeed resumes playback with sound. Now I can close this popup window and continue watching the video with sound.

**Comment by AllanWang** [comment] 2019-03-20 14:41
My question is whether it opened an overlay when playing videos before (ie PIP), or if it played automatically. The update basically made the device used to load content, so it has some newer settings. I have to verify if I'm causing the video to pause during clicks, or if that's just a website bug

**Comment by sreejithpm92** [comment] 2019-03-21 10:17
No it used to play within the timeline without opening an overlay...I think it's the apps problem sincr m.facebook.com doesn't have this problem

**Comment by robinbijlani** [comment] 2019-03-28 12:00
Same problem here. Let us know if we can provide more information to help debug this. It's my only frustration with Frost.

**Comment by AllanWang** [comment] 2019-03-28 19:03
Unfortunately I haven't been able to replicate the issue. If I disable PIP, the video plays inline and muting/unmuting works as expected.

The problem with the webview i s that many releases are launched per location, so it gets difficult to debug. It is weird that m.facebook.com doesn't have the problem when my app does.

Enabling autoplay also changes the layout, which might affect some things. I've had it disabled a while back, though I'm not sure where the setting is again, so I haven't tested with it enabled. (Autoplay is on through the desktop settings, though it's off on mobile)

**Comment by AllanWang** [comment] 2019-04-03 02:58
Duplicate of #1354; will be tracked there instead

I've identified the problem, though I don't have a good fix yet. It basically comes from the requirement of newer android versions to require user gestures before allowing audio. For some reason, pressing the unmute button doesn't count as a gesture for me. The quick fix would be to disable the requirement, but I'm going to see what others have to say

https://stackoverflow.com/questions/55486326/how-to-allow-audio-with-mediaplaybackrequiresusergesture-enabled

**Closed by AllanWang** 2019-04-03 02:58 UTC
Labels: bug, unverified
