### ISSUE TITLE
videos recently stopped playing

### ISSUE THREAD

**Issue by StevanWhite** [AllanWang/Frost-for-Facebook#1830] opened 2021-10-07 16:59 UTC
- [x ] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)
Yes, videos play just fine if I go to Facebook in the Chrome browser.

**Describe the bug**

Whenever a posting appears containing video, and I click on it, nothing happens at all.

**To Reproduce**

* Find a posting containing video, 
* Tap on it.
* Nothing happens at all.

This has been 100% recently (at least a few days)

**Details (please provide at least the app version):**
 - App Version: 3.1.0
 - Device: Cubot KingKong Mini
 - Android Version: 9.0

**Comment by AllanWang** [comment] 2021-10-08 02:23
Duplicate of #1808

**Closed as completed by AllanWang** 2021-10-08 02:23 UTC
Labels: bug, unverified
