### ISSUE TITLE
2.4.5 Update - Newly implemented expanding messaging text box not functioning

### ISSUE THREAD

**Issue by GibberMeJenks** [AllanWang/Frost-for-Facebook#1685] opened 2020-06-06 07:59 UTC
Hi @AllanWang! This is a continuation of #1655.

First off, thank you for the update to 2.4.5! I was very excited to see the expanding text box function added in. However, when sending a message today I noticed the text box did not expand (this is when responding or initiating a message to someone from an existing conversation string):

![Text box not expanding](https://user-images.githubusercontent.com/53843087/83939177-a0504b00-a78f-11ea-9e5b-7282189c6b76.PNG)

Is this a bug? The size of the text box when composing a new message to someone you never messaged before however, looks great:

![new message larger text box](https://user-images.githubusercontent.com/53843087/83939187-b78f3880-a78f-11ea-84e4-d9e573240745.PNG)

Not sure if it would be possible to make the text box the same size within an existing conversation as the one when composing a new message if the expanding doesn't work.

Thanks again for the hard work, and stay safe during this time! Let me know if you need more info!

**Comment by AllanWang** [comment] 2020-06-06 09:46
does this work in other places like newsfeed status?

**Comment by GibberMeJenks** [comment] 2020-06-06 20:51
Hi @AllanWang. When you create a new post (aka the 'what's on your mind' text box), the text box expands as you type and works perfectly:

![Create new post - text box expands](https://user-images.githubusercontent.com/53843087/83954265-a03a6480-a7fc-11ea-9201-44acff73d8d2.jpg)

It seems other areas like messaging, newsfeed, and commenting does not work and keeps the same size text box in my earlier posts.

**Comment by AllanWang** [comment] 2020-06-06 22:39
It works for me for composer and sending a message, but not commenting. There's a chance some sections have other hardcoded heights.

I'm also not sure why, but F-Droid is showing me a version 2.4.5 changelog with a 2.4.4 version, so it seems like it hasn't been updated for me

**Comment by AllanWang** [comment] 2020-11-10 03:29
Duplicate of https://github.com/AllanWang/Frost-for-Facebook/issues/1655

**Closed as completed by AllanWang** 2020-11-10 03:29 UTC
Labels: bug
