### ISSUE TITLE
Update 2.3.0 breaks dark themes

### ISSUE THREAD

**Issue by fluffynuts** [AllanWang/Frost-for-Facebook#1473] opened 2019-07-04 20:03 UTC
Just saw the update on F-Droid today and got it. After loading the app, Facebook page backgrounds are white. I tried toggling the theme to default and back to dark. I tried closing and reopening the app. Settings pages are fine - it's the site itself which isn't correct.

Downgrading to 2.2.4 gets dark themes back.

**Comment by AllanWang** [comment] 2019-07-05 00:55
Duplicate of https://github.com/AllanWang/Frost-for-Facebook/issues/1463

TL;DR wait for 2.3.1 on F-Droid or stay on 2.2.4

**Closed by AllanWang** 2019-07-05 00:55 UTC

**Comment by fluffynuts** [comment] 2019-07-05 04:22
Apologies. I did scan the open issue list, but didn't spot another similar issue.

**Comment by AllanWang** [comment] 2019-07-05 05:01
It's fine. I've had about 20+ emails anyways
