### ISSUE TITLE
[BUG] Frost has stopped working

### ISSUE THREAD

**Issue by tokenmath** [AllanWang/Frost-for-Facebook#1347] opened 2019-02-07 18:29 UTC
This is impossible to use. In weak connections the application stopped working, different from the "Face Slim" in that even with a bad internet connection it works normally

**Comment by AllanWang** [comment] 2019-02-07 18:30
Can you elaborate on stopped working? Does it crash? Does loading take long? Does it show a disconnected page? Do all tabs stop working?

**Comment by AllanWang** [comment] 2019-02-07 18:30
And what version are you using?

**Comment by tokenmath** [comment] 2019-02-07 18:41
@AllanWang On every page. Apparently, if you have a Wi-Fi or Mobile Data connection, the application will close slowly showing the error message "Frost has stopped working".
Already in fast connections it works normally

**Comment by tokenmath** [comment] 2019-02-07 18:42
@AllanWang 2.2.1

**Comment by AllanWang** [comment] 2019-02-07 18:44
It's probably related to #1323. I fixed it as of v2.2.2, which is available on github now, and pending fdroid at https://gitlab.com/fdroid/fdroiddata/merge_requests/4440

The problem is exclusively for the menu page, and it isn't 100% fixed. If you want to avoid the crash in general without upgrading you can remove the menu page in settings and replace it with something else.

You can reopen if the crash isn't fixed in the new version

**Closed by AllanWang** 2019-02-07 18:44 UTC
Labels: question
