### ISSUE TITLE
Separating the use of external apps and using messenger

### ISSUE THREAD

**Issue by nielubieprzemocy** [AllanWang/Frost-for-Facebook#1813] opened 2021-09-24 18:27 UTC
Hello,

First of all I really appreciate what you are doing. For my needs it exceeds anything else there is available. It's not something I can demand but.. please, keep up the good work! :)

To the point now. Would it be possible to separate the possibility to use messenger in the app and the option to use default system app to view external links (i.e. YouTube)? Right now it's seems to be one or another. It would be great to use messenger and Firefox/Newpipe/whatever to view external content.

Best of luck,
Marcin

**Comment by AllanWang** [comment] 2021-10-02 23:18
Duplicate of #1748

**Closed as completed by AllanWang** 2021-10-02 23:18 UTC
Labels: feature request
