### ISSUE TITLE
messages page not available (since a long time now)

### ISSUE THREAD

**Issue by r-flo-r** [AllanWang/Frost-for-Facebook#1899] opened 2022-06-18 16:18 UTC
- [x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)
via touch.facebook.com, there is only the messenger button. but not the messages icon on the top menu like in Frost.

**Describe the bug**
please note that i am using the german language version of the app - hopefully my failure description will be accurate to find the english corresponding entries of the apps:
on the second line of the top menu bar are four icons. first is the feed, second is the messages, third is the world icon, the fourth icon are the three dashes.
when i am trying to access the second one, the messages. it brings me the following error (in red text color):
Der Posteingang deiner Seite ist in der Facebook-App oder mobilen Web-Browsern aktuell nicht verfgbar. Du kannst deine Nachrichten über einen Desktop-Browser aufrufen odern indem du die Meta Business Suite oder den Messenger im App Store herunterlädst.
below that message there is a link "back to the startpage" (zurück zur startseite)

its now for that for a very long time (quite a year?), before that receiving and writing messages was possible with Frost.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'second icon in lower top menu for messages'
2. See error

**Details (please provide at least the app version):**
 - App Version: 3.1.2
 - Device: Samsung S10e
 - Android Version: 11

**Logs/Screenshots:**

where to get logs?

please advise and i can provide a sreenshot

**Comment by devurandom** [comment] 2022-07-28 04:52
Duplicate of #1790?

**Comment by RokeJulianLockhart** [comment] 2022-07-28 18:55
Actually, @devurandom, I believe that https://github.com/AllanWang/Frost-for-Facebook/issues/1790 is the duplicate of https://github.com/AllanWang/Frost-for-Facebook/issues/1899, because that issue was reported approximately one month subsequently.

**Comment by AllanWang** [comment] 2022-09-16 03:13
Grouping with #1790. Both are the same cause for messages, in that Facebook has disabled it in some regions. Follow up in that thread is why messenger does not work

**Closed as completed by AllanWang** 2022-09-16 03:13 UTC
Labels: bug, unverified
