### ISSUE TITLE
TimberLogger.kt line 65

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#132] opened 2017-08-09 02:46 UTC
#### in ca.allanwang.kau.e.b.a

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/598a7793be077a4dcccf1ac1?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/598a7793be077a4dcccf1ac1?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment] 2017-08-10 02:23
Duplicate of #111

**Closed by AllanWang** 2017-08-10 02:23 UTC
Labels: non-fatal marker
