### ISSUE TITLE
Messages tab should use messenger.com

### ISSUE THREAD

**Issue by zerodogg** [AllanWang/Frost-for-Facebook#1746] opened 2021-01-14 06:28 UTC
This actually does occur on touch.facebook.com as well, since they've removed the messenger bits.

**Describe the bug**
The current messages tab of frost directs to m.facebook.com/messages (or touch.facebook.com/messages).
This no longer exists. It should direct to messenger.com instead.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use the messages tab
2. Get error from facebook about a "broken link"

**Details (please provide at least the app version):**
 - App Version: 2.4.7
 - Device: Fairphone 3
 - Android Version: 10

**Comment by AllanWang** [comment] 2021-01-14 09:49
Please search through existing issues before making a new one. Duplicate of #1732, which is also the most active issue for now.

**Closed as completed by AllanWang** 2021-01-14 09:49 UTC
Labels: bug, unverified

**Comment by zerodogg** [comment] 2021-01-14 09:57
I did search. "Messages from application stops working" did *not* strike me as being the same this issue.
