### ISSUE TITLE
Swiping uploaded images triggers swipe left

### ISSUE THREAD

**Issue by wvffle** [AllanWang/Frost-for-Facebook#1427] opened 2019-05-24 17:26 UTC
**Describe the bug**
After I tried to upload some images for my friend and I wanted to check the first image, I had to swipe to the left (I uploaded more than 7 images). It triggered swipe to the left tab even though i had my finger in horizontally scrolled div.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to conversation
2. Upload a couple of images
3. Try to swipe images to check the first one

**Details (please provide at least the app version):**
 - App Version: 2.4.4
 - Device: Ulefone Armor 3
 - Android Version: 8.1.0

**Comment by AllanWang** [comment] 2019-05-25 04:00
This has been sort of a known issue for quite some time, with a workaround.
Frost currently doesn't check for horizontal scroll availability in the webview.
You may optionally:
* Disable swiping on overlays altogether in settings
* Long press before swiping, which disables horizontal scrolling temporarily. This will cause problems for elements with long press context though.

If there's an elegant way to detect horizontal scrolling options through js, I'd be open to suggestions though. The long press alternative isn't great. Detection would need to know that the element supports horizontal scrolling, and must also know that it has the possibility of scrolling left.

**Comment by wvffle** [comment] 2019-05-25 07:50
I don't know kotlin much but I'd try to fix it if I could. You can check if any of the parent elements has `scrollLeftMax` higher than `0`

```js
function checkHorizontalScroll (el) {
  if (!el) return false
  if (el.scrollLeftMax) return true
  return checkHorizontalScroll(el.parentElement)
}
```

**Comment by AllanWang** [comment] 2019-05-25 13:10
I'll look into its performance. The problem is making the experience seamless since any js response is async and could happen after I register the event in Android first

**Comment by wvffle** [comment] 2019-06-20 10:22
Maybe change tabs only when swiped from the side of the screen?

I also found this: https://stackoverflow.com/a/4695318/5565538

**Comment by AllanWang** [comment] 2019-06-20 17:04
I'm not very convinced that there is a solution without using javascript, given that it would be quite complex to expose such apis. Stuff like the "people you may know" content isn't a part of the main body.

I will take a look to see how it works, but even in the solution there are people who complain that it doesn't.

**Comment by AllanWang** [comment] 2019-06-20 17:05
If you want a fix on the main panel though, you can already disable swipes in the viewpager. For the pop up overlay, you can enable it to only close when swiped from the edge

**Comment by AllanWang** [comment] 2019-07-02 23:30
Fixed by pretty much just checking `scrollWidth` and `offsetWidth`

**Closed** 2019-07-03 01:37 UTC
Labels: bug, help wanted
