### ISSUE TITLE
Logged out when trying to switch users

### ISSUE THREAD

**Issue by MostWanted-Hub** [AllanWang/Frost-for-Facebook#1795] opened 2021-09-11 14:51 UTC
**Describe the bug**

So I add my second account thats meme focused and all is well until i click on the icon or switch user to change account, then the OG account disappears and then I click on the new one and so does that, tried multiple times to try to switch account without being logged out but I'm having no luck  , IDK why it wants to forget both the accounts

Details :
 - App Version: 3.0.0
 - Device: Black shark 4
 - Android Version: 11

**Comment by AllanWang** [comment] 2021-09-12 08:32
Duplicate of #1753

**Closed as completed by AllanWang** 2021-09-12 08:32 UTC
Labels: bug, unverified
