### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by puppykickr** [AllanWang/Frost-for-Facebook#1394] opened 2019-04-11 17:08 UTC
**Describe the bug**
No Audio When Playing Videos From Messages

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'messages'
2. Click on 'any given video'
3. Video will play without audio.
4. When audio is unmuted, the video stops playing altogether.
5.  If audio is muted again, the video will resume playing, without audio.
6. The video will not play at all if the audio is on.

**Expected behaviour**
Videos should play with audio.

**Screenshots**
Will make screen recording if applicable.

**Details (please provide at least the app version):**
 - App Version: 2.2.2
 - Device: ZTE 558VL & Probano VLE
 - Android Version: 7.1.1 & 8.1.0

**Additional context**

**Comment by AllanWang** [comment] 2019-04-11 17:10
Duplicate of #1368. Snapshot build is available at https://github.com/AllanWang/Frost-for-Facebook/pull/1383

I'm currently nearing finals so I haven't had time to release anything

**Closed by AllanWang** 2019-04-11 17:10 UTC
