### ISSUE TITLE
The whole view moves up/down by showing/hiding the top bar when horizontal scrolling

### ISSUE THREAD

**Issue by pkillnine** [AllanWang/Frost-for-Facebook#1236] opened 2018-12-12 16:50 UTC
To reproduce:
 - Disable the setting that changes the tab by horizontal scrolling.
 - Drag a carousel horizontally (e.g. 'People you may know'), and without letting go, drag vertically - The top bar will hide/show.

This is related to https://github.com/AllanWang/Frost-for-Facebook/issues/1225

**Comment by AllanWang** [comment] 2018-12-12 17:50
Are you dragging horizontally and then vertically without letting go? #1225 may not be related as it was just to remind me to find better options for horizontal scroll when tab scrolling is enabled

**Comment by pkillnine** [comment] 2018-12-12 17:54
Yes i am, I've updated the bug report to be more clear about that

**Comment by AllanWang** [comment] 2018-12-12 18:00
Okay. As of now that is expected behaviour since the webview does not consume the vertical movements. If I had a way of knowing (accurately) when the webview could scroll horizontally so I can stop the tab bar from moving, then I'd also be able to solve the problem of knowing when a horizontal scroll would move the webview vs a tab.

There are solutions, but as the events in a webview aren't native, they aren't very elegant.

As a future note to myself, I could lock vertical movements whenever any horizontal movement is applied

**Comment by pkillnine** [comment] 2018-12-12 21:09
Oh that reminds me of a feature request I wanted to make that would fix this, I just posted it (https://github.com/AllanWang/Frost-for-Facebook/issues/1237)

**Comment by AllanWang** [comment] 2019-04-14 00:29
Closing for #1225, though I still don't have a good solution for this

**Closed by AllanWang** 2019-04-14 00:29 UTC
Labels: enhancement
