### ISSUE TITLE
Unable to copy text from longer FB posts

### ISSUE THREAD

**Issue by yoyob1** [AllanWang/Frost-for-Facebook#1330] opened 2019-01-21 05:09 UTC
Unable to copy the text from lengthier posts (the posts with 'more' option, if I try to copy the text in the expanded post, (after clicking 'more', the copy text option is not there. can you add this feature in the next release. i will be very thankful.

**Comment by AllanWang** [comment] 2019-01-21 05:11
Duplicate of #454 

It's been a long time request that I will try to get to in future updates.

**Closed by AllanWang** 2019-01-21 05:11 UTC
