### ISSUE TITLE
file browser not found

### ISSUE THREAD

**Issue by Michas0206** [AllanWang/Frost-for-Facebook#1815] opened 2021-09-25 08:36 UTC
I cant upload images or videos anymore since update to 3.10 today - it tells "file browser not found" when clicking on the symbol to post a photo.

Lineage OS / Android 11

**Comment by DestyNova** [comment] 2021-09-25 17:39
Looks like a duplicate of #1806

**Comment by AllanWang** [comment] 2021-09-25 23:58
Duplicate of #1806

**Closed as completed by AllanWang** 2021-09-25 23:58 UTC
Labels: bug, unverified
