### ISSUE TITLE
enhancement request: get rid of false notifications

### ISSUE THREAD

**Issue by gothmog123** [AllanWang/Frost-for-Facebook#1670] opened 2020-04-07 15:35 UTC
Just like the title says. One example is when I send a message on the desktop, Frost on my mobile device will notify me of my own message.

Also received messages will sometimes generate additional notifications even after they're read.

Thank you.

**Comment by AllanWang** [comment] 2020-04-18 22:24
Sounds like the check for what message is or is not read is messed up in your situation. I'll take a look at my own message, but if it works on my end, that may mean you have a different site version on your end. If you are familiar with CSS, I would need to know the class items when a message is read or unread.

As for your first problem, that's likely a result of the second problem. Messages you send should not be marked as unread by Facebook, and should have been filtered out

**Comment by GibberMeJenks** [comment] 2020-06-07 01:08
@gothmog123 @AllanWang  when you use facebook in your desktop, do you have a filter in adblock that blocks the script when you read someone's message? For example, when you read someone's message the filter does not send to the sender the 'seen' notification indicating that you read their message.

I have this filter activated in my desktop for Facebook and it contributes to your problem since when you're on Frost it thinks you haven't read the message and subsequent messages hence the 'false' notification.

This never bothered me too much so I never reported it but if you have this filter to block facebook from sending the message 'seen' notification to your friends after reading their message, it is one of the causes for this issue.

**Comment by gothmog123** [comment] 2020-06-07 15:59
> @gothmog123 @AllanWang when you use facebook in your desktop, do you have a filter in adblock that blocks the script when you read someone's message? For example, when you read someone's message the filter does not send to the sender the 'seen' notification indicating that you read their message.
> 
> I have this filter activated in my desktop for Facebook and it contributes to your problem since when you're on Frost it thinks you haven't read the message and subsequent messages hence the 'false' notification.
> 
> This never bothered me too much so I never reported it but if you have this filter to block facebook from sending the message 'seen' notification to your friends after reading their message, it is one of the causes for this issue.

Thanks, I don't really know. I'm using Brave with its standard block lists. Am I blocking seen notifications then?

**Comment by AllanWang** [comment] 2020-06-28 06:31
I don't know enough about the brave browser, but I think this is a conflict with something you have installed. Closing for now until more people report it

**Closed as completed by AllanWang** 2020-06-28 06:31 UTC
Labels: bug, unverified
