### ISSUE TITLE
Larger compose window for comments

### ISSUE THREAD

**Issue by soapee01** [AllanWang/Frost-for-Facebook#1700] opened 2020-07-25 13:48 UTC
Is it possible to make the composition window for a comment full or half screen? It's really difficult to type comments longer than a sentence or two in Facebook.

Fantastic app, and thank you for all of your work!

**Comment by AllanWang** [comment] 2020-08-26 23:31
Marking as duplicate of #1655. If the problem is separate, feel free to comment again. The fix will ideally apply to all text boxes

**Closed as completed by AllanWang** 2020-08-26 23:31 UTC
