### ISSUE TITLE
ContentUriUtils.java line 188

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#427] opened 2017-10-18 15:45 UTC
#### in org.chromium.base.ContentUriUtils.getDisplayName

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59e7770461b02d480dc9be27?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59e7770461b02d480dc9be27?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment] 2017-10-18 19:32
Duplicate of #414

**Closed by AllanWang** 2017-10-18 19:32 UTC
