### ISSUE TITLE
Unable to post images

### ISSUE THREAD

**Issue by Beastie71** [AllanWang/Frost-for-Facebook#1822] opened 2021-09-26 20:21 UTC
I've tried restarting the application and the phone.  Just installed 3.1.0, let me know what additional information I can provide.  Attached is an image with the error at the bottom.  Fine chooser not found

![Screenshot_20210926-160918](https://user-images.githubusercontent.com/5488633/134822860-25ab20f2-deb9-4083-8b28-0c2cd0cbb55a.png)

**Comment by syphyr** [comment] 2021-09-26 20:38
https://github.com/AllanWang/Frost-for-Facebook/issues/1806

**Comment by AllanWang** [comment] 2021-09-26 21:50
Duplicate of #1806, see #1819

**Closed as completed by AllanWang** 2021-09-26 21:50 UTC
