### ISSUE TITLE
Can No Longer Tap Photo After Doing A Search

### ISSUE THREAD

**Issue by puppykickr** [AllanWang/Frost-for-Facebook#1588] opened 2019-11-26 08:30 UTC
- [ √] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**

When performing a search, photos come up.
When selecting a photo, a message comes up stating that the webpage is not available.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...' SEARCH
2. ENTER SEARCH INFO
3. Click on '....' PHOTO

**Details (please provide at least the app version):**
 - App Version: 2.4.1
 - Device: ZTE558VL 
 - Android Version: 7.1.1

**Comment by puppykickr** [comment] 2019-11-26 08:31
![Screenshot_2019-11-26_02-27-39](https://user-images.githubusercontent.com/44860287/69612092-b1581c80-0ff4-11ea-95a1-9684706cfe3b.png)

This is the result when tapping a photo in the search results.

**Comment by AllanWang** [comment] 2019-11-26 08:49
Duplicate of #1586

**Closed as completed** 2019-11-26 08:49 UTC
Labels: bug, unverified

**Comment by puppykickr** [comment] 2019-11-26 09:30
Sorry about that.
