### ISSUE TITLE
group bug

### ISSUE THREAD

**Issue by duergrim** [AllanWang/Frost-for-Facebook#1449] opened 2019-06-18 07:44 UTC
Hey there.
I have dark mode enabled, and when I go to menu > groups, this is what I see
![Screenshot_20190617-121505](https://user-images.githubusercontent.com/44030905/59662648-a9768f80-91ad-11e9-8590-5b19d0aea289.jpg)

**Comment by duergrim** [comment] 2019-06-18 07:45
Just to be sure you understand my issue - I can't read the names of the groups

**Comment by AllanWang** [comment] 2019-06-18 17:24
Duplicate of #1431, fixed in #1443.

A new update is already available through github releases, but if you downloaded through F-Droid you'll have to wait until they add it

https://gitlab.com/fdroid/fdroiddata/merge_requests/4958

**Closed by AllanWang** 2019-06-18 17:24 UTC
Labels: bug, unverified
