### ISSUE TITLE
FrostViewPager.kt line 26

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#356] opened 2017-10-01 05:52 UTC
#### in com.pitchedapps.frost.views.FrostViewPager.onTouchEvent

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59d082b9be077a4dcc8e12bb?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59d082b9be077a4dcc8e12bb?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment] 2017-10-10 17:47
Duplicate of #112 ; on touch index not caught?

**Closed** 2017-10-12 16:36 UTC
Labels: bug
