### ISSUE TITLE
App will not log in

### ISSUE THREAD

**Issue by yasqun** [AllanWang/Frost-for-Facebook#1769] opened 2021-04-08 20:26 UTC
When trying to log into Facebook through the app it gives the following error:
"Logging into this app with Facebook is not available at this time."

Steps to reproduce the behaviour:
1. Go to log in page
2. Type in email and password
3. See error

 - App Version: 3.0.0
 - Device: Samsung Note 9 SM-N960F
 - Android Version: 10

**Comment by snowkeld** [comment] 2021-04-12 16:44
I can confirm this behavior. I removed all local data and tried with a clean install of frost with same result.
Facebook logged me out in the middle of using the app, cannot log back in. 

Facebook error top of login says "Logging into this app with Facebook is not available at this time."

Not an account issue, logged in elsewhere with no issues.

**Comment by brozkeff** [comment] 2021-04-18 19:37
confirmed with 2.4.7 as well as 3.0.0, android10/miui12, redmi note 8t

**Comment by kubovo** [comment] 2021-04-19 08:26
I confirm this behavior with v3.0.0, Android 11 (stock Pixel).
Just downloaded the app from F-Droid, first use.
I suspect it might be related to Facebook Inc. steps against web wrappers: https://www.androidpolice.com/2021/04/18/facebook-bullies-third-party-apps-swipe-and-simple-social-into-oblivion/

**Comment by AllanWang** [comment] 2021-04-22 09:40
Non actionable on my end, but Facebook also does that from time to time. You can provide an update if it works again. 

While I've never received a cease and desist letter from Facebook, Frost was removed from the Play Store years ago. We have unfortunately all violated play policies, but I don't see how they can check against web wrappers on login. Maybe they'd detect it over time and log you out, or they're really just phasing out the mobile site, in which there's still nothing I can do.

**Comment by kubovo** [comment] 2021-04-22 10:18
@AllanWang Thanks for the input. I was actually Simple for Facebook user (another FB web wrapper), and this one still works for me - I've never logged out so far. Because of the events mentioned in the article, I've started to look for alternative app, but all of the other wrappers don't let me through login ("Logging into this app with Facebook is not available at this time."). Only thing that works is the m.facebook.com website through browser. That is why I was under impression that they are doing some kind of internal check there... But I can see that there is nothing you can do about that on your side.

**Comment by Lazza** [comment] 2021-04-25 14:54
Same issue here, with several different apps. The last I tried, Friendly, got the same error but it has a "desktop website" mode. I turned that on and I was able to login successfully, then I turned it off again. 

Maybe you could try this approach.

**Comment by AllanWang** [comment] 2021-04-26 18:31
I don't plan on adding facebook.com support until necessary. For desktop mode, I already have a desktop user agent, which is required to access some pages. Others can modify it and build their own variant to test around, or switch the url.

They are at https://github.com/AllanWang/Frost-for-Facebook/blob/dev/app/src/main/kotlin/com/pitchedapps/frost/facebook/FbConst.kt

and the CI can build apks on your behalf

**Comment by Lazza** [comment] 2021-04-26 18:34
Sorry but English is not my first language, could you clarify what you mean by "I don't plan on adding facebook.com support"?

Thank you.

**Comment by AllanWang** [comment] 2021-04-26 20:59
Frost uses m.facebook.com, which is a mobile view for facebook (accessible from any device). The true desktop view is facebook.com, but it's super bloated and will take forever to load on a mobile device. It isn't worth pursuing for that reason. Messenger.com is a desktop oriented site and it's already really bad performance wise

**Comment by Lazza** [comment] 2021-04-26 21:12
Now I understand, thank you. I probably did not express my suggestion very well previously.

I am not suggesting that Frost uses the desktop version "in general", it is just needed for the first login. After the login, one can instantly switch to `m.facebook.com` retaining the cookies and stuff.

This allows users to sign-in bypassing the block that is otherwise encountered.

While the user is not yet logged in on Facebook, the login form (desktop version) is actually quite fast.

**Comment by john5788** [comment] 2021-04-29 08:49
Reporting that I am seeing the same issue recently.

Frost was working for me, then suddenly last week, Facebook forced me to log out on Frost. Attempts to log in were blocked with "Logging into this app with Facebook is not available at this time."

I read through this thread and tried using Friendly with "desktop version" enabled. Logging in was fine, asked for my 2FA code, then switching off desktop version and using Facebook through Friendly was fine. Otherwise logging in the normal way with Friendly was also blocked with "Logging into this app with Facebook is not available at this time.".

I switched from Friendly to Frost because of the bugs. Looks like I am temporarily switching back until Frost works for me again.

**Comment by AllanWang** [comment] 2021-04-29 22:13
I take it the desktop version is the actual desktop site? Can someone post a screenshot of it (sign in screen before logging in)?

**Comment by john5788** [comment] 2021-04-30 03:18
![Screenshot_20210429-195958_Friendly](https://user-images.githubusercontent.com/9289163/116644384-0dc91500-a928-11eb-8bda-bfd77cd829e6.png)

Attached a screenshot of Friendly in desktop mode.

**Comment by xisonc** [comment] 2021-05-29 00:18
I think the issue may be whether you have 2FA enabled on your account.

Frost works for my wife, but not myself. I have 2FA using TOTP enabled, my wife does not.

**Comment by john5788** [comment] 2021-05-29 18:42
> I think the issue may be whether you have 2FA enabled on your account.
> 
> Frost works for my wife, but not myself. I have 2FA using TOTP enabled, my wife does not.

I just disabled 2FA and tried to log in with Frost and still cannot log in.

**Comment by GottHeit** [comment] 2021-06-09 10:51
Same for me, but with all different wrapper (Frost, Slim, Tinfoil,...) 

There is a quickly disappearing message saying that the browser is not supported by the app when launching Frost. Maybe it is possible to mask the "browser version" or bypassing it with an alias?

Set up a new phone yesterday (Pixel 5 cause my other Pixel 5 touched the floor). On the old one it is working, but not on the new one...

Tinfoil has the option to choose a desktop version (but it is super old, so not sure if it is still working properly) and that does not work for me...

**Comment by john5788** [comment] 2021-06-13 22:05
A new error message is being displayed now.

"For your account security, logging into Facebook from an embedded browser is disabled."

Attaching a screenshot.
![Screenshot_20210613-150314_Frost](https://user-images.githubusercontent.com/9289163/121823228-bfae6d80-cc58-11eb-9ef5-88f55c3c26dd.png)

**Comment by AllanWang** [comment] 2021-06-14 05:11
Well, that doesn't sound very good. Not sure how facebook checks for embedded browsers; if this happens for me, I'll try to look into how to work around it, but otherwise, I guess this marks the end of third party apps. I don't use facebook enough to want to install their app, but my use case is also limited to just getting notifications vs porting all the features over to a new app

**Comment by Lazza** [comment] 2021-06-14 09:43
The wording of the message has changed but it's the same check they did back in April.

**Comment by nermolov** [comment] 2021-06-20 15:39
Confirming I get the same issue of "For your account security, logging into Facebook from an embedded browser is disabled."

**Comment by redtux** [comment] 2021-06-26 08:34
I am having the same issue as @john5788 and cannot log in via Frost anymore. I have been logged out, had to confirm my cookies settings, and then - after trying to log in - I get the same message as shown in the screenshot.
> For your account security, logging into Facebook from an embedded browser is disabled.

**Comment by raphus-cys** [comment] 2021-07-27 08:51
found a workaround from an unrelated post on reddit: tap on forgot password -> mobile number -> enter password -> enter 2fa (my 2fa enabled, not sure if it would work without) and voila!

**Comment by john5788** [comment] 2021-07-31 18:41
> found a workaround from an unrelated post on reddit: tap on forgot password -> mobile number -> enter password -> enter 2fa (my 2fa enabled, not sure if it would work without) and voila!

This seems to work for me.

**Comment by ygordreyer** [comment] 2021-08-09 17:41
> found a workaround from an unrelated post on reddit: tap on forgot password -> mobile number -> enter password -> enter 2fa (my 2fa enabled, not sure if it would work without) and voila!

It works! Perfect, thanks for sharing!

**Comment by AllanWang** [comment] 2021-09-12 08:31
Glad to see there's a solution. Closing for now since issues like these won't be addressable by me anyways. Most I could do is maybe change the cookie, but if this happens again, we're generally out of luck on the app side.

**Closed as completed by AllanWang** 2021-09-12 08:31 UTC
Labels: bug, unverified
