### ISSUE TITLE
[Bug]Frost scrolls up to 'default bottom' when writing more then a 3 lines in messages, which hides everything beneath the keyboard.

### ISSUE THREAD

**Issue by hovercats** [AllanWang/Frost-for-Facebook#1704] opened 2020-08-07 13:24 UTC
Every time I write more than 3 lines in messenges, it continues behind the keyboard, where I cant see what Im typing. If I scroll down to see, it scrolls back up when I start typing again.

I reinstalled the app to verify if the problem still persist, which it did. 

Oneplus 6 
Omnirom 10
Frost 2.4.5

**Comment by hovercats** [comment] 2020-08-08 14:34
I can verify that downgrading to 2.4.4 fixes the issue as of now, upgrading to 2.4.5 again will make the issue appear again.

**Comment by AllanWang** [comment] 2020-08-26 23:23
Seems like a bug with the auto expanding script I have. If this continues to be an issue I will add options to disable it. The goal was to allow people to see the entire textbox, since by default you only get max 3 lines or so. Not too sure why it's affecting some users and not others, as I test on a Oneplus 6t

**Comment by gbakeman** [comment] 2020-09-18 23:02
I don't know if it helps much at this point, but I'm also seeing this bug on my OnePlus 6T (Android 9). I like the idea of the autoexpanding textbox, is it possible the script could be modified such that it makes sure the cursor is always visible to the user whenever the textbox expands? I don't know what functions are available to accomplish this, perhaps just by checking if the bottom of the textbox is above the keyboard or atleast the page is scrolled up as much as possible?

**Comment by AllanWang** [comment] 2020-10-04 02:48
Marking as duplicate of https://github.com/AllanWang/Frost-for-Facebook/issues/1655 to keep the conversation in one place. This is an implementation bug, and the next version will have a way to disable auto expansion. Will take a look to see how scrolling affect text box resizing, but unfortunately I'll only be able to support the feature for whatever behaviour all of my devices have.

**Closed as completed by AllanWang** 2020-10-04 02:48 UTC
Labels: bug, unverified
