### ISSUE TITLE
No Messages on Facebook Zero

### ISSUE THREAD

**Issue by VR-25** [AllanWang/Frost-for-Facebook#1595] opened 2019-12-14 20:20 UTC
When using Facebook zero balance version (subdomain `0`, `free` or `zero`), the messages tab won't load.

**Comment by AllanWang** [comment] 2019-12-15 21:32
Everything else is working fine? Do carriers auto direct m.facebook.com to 0.facebook.com? All the pages are hardcoded to use `m`, so I wonder if the problem is something else

**Comment by VR-25** [comment] 2019-12-18 17:08
```
/
/profile
/home.php
/notifications
```
All of these work (i.e., get redirected to the `free` subdomain).

`/messages` gives me a timeout error, and it's redirected to the `mobile` subdomain - as shown below. I tested this on several browsers - same issue.
```
Webpage not available

The webpage at https://mobile.facebook.com/messages?_rdc=1&_rdr could not be loaded because:

net::ERR_TIMED_OUT
```
A workaround would be loading `/` or `/home.php` after the timeout. From there, users can go to messages.

Since we're talking about messages, is it feasible to fetch message notifications from `0`, `free` and `mbasic` subdomains (no JavaScript support)? This would be another great addition.

**Comment by AllanWang** [comment] 2019-12-19 17:36
Does messenger.com work with zero? It could be that zero is expected for mobile only, and messages on frost requires a desktop user agent. If you want you can test if it works in your browser while in desktop mode

**Comment by AllanWang** [comment] 2019-12-19 17:37
I don't think I've seen a "mobile" domain though

**Comment by VR-25** [comment] 2019-12-19 18:29
No, messenger.com doesn't work with zero.
The user agent is irrelevant. In addition to several mobile and desktop UAs, I tried bots and even the string "Facebook". The results were the same in all cases.
It's obvious now that Frost has nothing to do with this issue. It's a Facebook/carrier's fault.
Where do we go from here? Any ideas besides the one I suggested?

**Comment by AllanWang** [comment] 2019-12-26 19:44
I'm not really willing to support new subdomains, since that means all features + theming need to be tested on each new variant. It's next to impossible to add automated testing per build in a way that won't jeopardize my own accounts. Having a redirect using the same domain is feasible, though I do wonder how many users are affected by that. A potentially better method would be to just disable the tabs and show Facebook's original header

**Comment by AllanWang** [comment] 2019-12-30 18:56
Closing as there's no actionable items on my end.

**Closed as completed by AllanWang** 2019-12-30 18:56 UTC
Labels: question
