### ISSUE TITLE
Auto play settings page from the app settings shows page not found

### ISSUE THREAD

**Issue by abhishekabhi789** [AllanWang/Frost-for-Facebook#1626] opened 2020-01-31 12:38 UTC
**AutoPlay settings page not opening in the app**
While clicking on Settings - Behaviour - Autoplay Settings, a facebook error page with broken thumb says **Page Not Found!**
Page link copied from frost: https://m.facebook.com/settings/videos/
**To ReproduceVersion**
Steps to reproduce the behaviour:
1. Go to Frost For Facebook app settings
2. Click on 'Behaviour'
3. Tap on 'Autoplay Settings'
5. See error

**Details:**
 - App Version: Version 2.4.2
 - Device: Xiaomi Redmi Note 4
 - Android Version: 10

**Comment by syphyr** [comment] 2020-01-31 12:48
https://github.com/AllanWang/Frost-for-Facebook/commit/da2405f42d8ca1868028e3a5717292468f1ddf5c

**Comment by AllanWang** [comment] 2020-02-02 09:27
Duplicate of #1612

**Closed as completed by AllanWang** 2020-02-02 09:27 UTC
Labels: bug, unverified
