### ISSUE TITLE
Dark Theme - White Feed Background

### ISSUE THREAD

**Issue by stathism27** [AllanWang/Frost-for-Facebook#1463] opened 2019-07-02 22:25 UTC
I have updated the Frost to the latest version and I noticed that the dark theme works fine for every section of the app except for news feed,that used to work before the update.

- version 2.3.0 - Xiaomi Redmi 4X

**Comment by 3drinks** [comment] 2019-07-02 22:36
Can confirm, and adding; white background is on messenger screen too, although yes the messenger redirect seems gone thankfully.

**Comment by AllanWang** [comment] 2019-07-02 22:39
Weird. The user agent didn't change and there hasn't been much theme changes

https://github.com/AllanWang/Frost-for-Facebook/compare/v2.2.4..v2.3.0

Is the theme broken or does it look like it isn't applying at all?

**Comment by 3drinks** [comment] 2019-07-02 22:41
The theme itself looks fine and behaves as intended, except for TL and messenger having a forced white background.

**Comment by AllanWang** [comment] 2019-07-02 22:42
I guess what I'm asking is if the text is white (expected in dark mode), and there is just one main element in the background that has a white background. If so, perhaps one of you can send me the html page or use inspect element to fix it? I can't replicate it myself

**Comment by AllanWang** [comment] 2019-07-02 22:43
From what someone else sent me it looks like messages isn't themed at all

**Comment by 3drinks** [comment] 2019-07-02 22:44
Text ie default black and with a white background. Yes, not themed is a good descriptor as it looks generic.

**Comment by AllanWang** [comment] 2019-07-02 22:45
If you click a post and launch the overlay, is it themed there too? It sounds like the css just isn't applying. Notifications and menu are native ui so they don't use css

**Comment by 3drinks** [comment] 2019-07-02 22:46
Clicking a post still shows them on default skin.

**Comment by AllanWang** [comment] 2019-07-02 22:47
Nvm I can replicate the problem. I rely on the builder to generate the css and I forgot fdroid doesn't do that. Stay on 2.2.4 for now

**Comment by 3drinks** [comment] 2019-07-02 22:49
Acknowledged.

**Comment by AllanWang** [comment] 2019-07-03 01:37
This'll be resolved with #1464

**Closed by AllanWang** 2019-07-03 01:37 UTC
Labels: CSS
