### ISSUE TITLE
Video stories won't open

### ISSUE THREAD

**Issue by carlosnewmusic** [AllanWang/Frost-for-Facebook#1833] opened 2021-10-09 07:45 UTC
- [x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
Stories that contain video cannot be opened even if you give the play

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to feed
2. Click on story
3. View a story that contains video
4. Hit the play
4. Not seen, the video does not open

**Details (please provide at least the app version):**
 - App Version: 3.1.0
 - Device: Sony Xperia XA2
 - Android Version: 9

**Comment by AllanWang** [comment] 2021-10-10 05:48
Duplicate of #1808

**Closed as completed by AllanWang** 2021-10-10 05:48 UTC
Labels: bug, unverified
